apiVersion: v1
kind: Namespace
metadata:
  name: paaruwa-agent
  labels:
    environment: nprod
    projectname: psi-nprod
    owner: Chamila.Wijayawardhana
    applicationname: psi-nprod-apps
    department: product-and-service-innovation
    cxoname: Viranga-Senevirathna
    budgetcode: DOSU1701
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paaruwa-resort-agent
  namespace: paaruwa-agent
  labels:
    app: paaruwa-resort-agent
    environment: nprod
    projectname: psi-nprod
    owner: Chamila.Wijayawardhana
    applicationname: psi-nprod-apps
    department: product-and-service-innovation
    cxoname: Viranga-Senevirathna
    budgetcode: DOSU1701
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paaruwa-resort-agent
  template:
    metadata:
      labels:
        app: paaruwa-resort-agent
        environment: nprod
        projectname: psi-nprod
        owner: Chamila.Wijayawardhana
        applicationname: psi-nprod-apps
        department: product-and-service-innovation
        cxoname: Viranga-Senevirathna
        budgetcode: DOSU1701
    spec:
      containers:
      - name: agent
        image: psi-nprod-registry.tencentcloudcr.com/paaruwa-agent/paaruwa-resort-agent:v2
        envFrom:
        - secretRef:
            name: paaruwa-resort-agent-secrets
        volumeMounts:
        - name: gcp-credentials
          mountPath: /app/gcp-credentials.json
          subPath: gcp-credentials.json
          readOnly: true
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
            ephemeral-storage: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
            ephemeral-storage: "4Gi"
      volumes:
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials
      # Give active calls up to 15 minutes to finish before shutting down
      terminationGracePeriodSeconds: 900
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: paaruwa-resort-agent-scaler
  namespace: paaruwa-agent
  labels:
    environment: nprod
    projectname: psi-nprod
    owner: Chamila.Wijayawardhana
    applicationname: psi-nprod-apps
    department: product-and-service-innovation
    cxoname: Viranga-Senevirathna
    budgetcode: DOSU1701
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paaruwa-resort-agent
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Spin up a new pod early before the first one fills up!
